# docker-compose.test.yml
version: '3.8'

services:

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    container_name: backend-test
    environment:
      - NODE_ENV=test
      - PORT=5000
      - MONGO_URI_TEST=mongodb://root:rootpassword@mongodb-test:27017/feelgptdbtest?authSource=admin&directConnection=true
      - MONGO_URI=mongodb://root:rootpassword@mongodb-test:27017/feelgptdbtest?authSource=admin&directConnection=true
      - AZURE_PHI_ENDPOINT=your_test_endpoint
      - AZURE_PHI_API_KEY=your_test_api_key
    depends_on:
      - mongodb-test
    networks:
      - feelgpt-test-network
    command: ["npm", "test"]

  mongodb-test:
    build:
      context: ./database/mongodb_rs
      dockerfile: Dockerfile
      args:
        MONGO_VERSION: 4.4
    container_name: mongodb-test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=feelgptdbtest
      - MONGO_REPLICA_PORT=27017
      - MONGO_REPLICA_HOST=host.docker.internal
    ports:
      - "27018:27017"  # Exposed on 27018 to avoid conflicts with production
    restart: always
    networks:
      - feelgpt-test-network
    volumes:
      - mongo_test_data:/data/db

networks:
  feelgpt-test-network:
    driver: bridge

volumes:
  mongo_test_data:
