version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-prod
    ports:
      - "3000:3000"
      - "3001:80"
    environment:
      - MY_REACT_APP_BACKEND_URL=http://localhost:5001/api/v1
    networks:
      - feelgpt-network
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: backend-prod
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/feelgptdbprod?authSource=admin&directConnection=true
    networks:
      - feelgpt-network
      
networks:
  feelgpt-network:
    external: true