version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
      - "3001:80"
    environment:
      - MY_REACT_APP_BACKEND_URL=http://localhost:5000/api/v1
    networks:
      - feelgpt-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017
    networks:
      - feelgpt-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - feelgpt-network

networks:
  feelgpt-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local