# Use a base image with Node.js
FROM node:16

# Set the working directory to /app
WORKDIR /app

# Copy the tests package.json and package-lock.json to the container
COPY ./tests/package.json ./tests/package-lock.json ./

# Install necessary Node packages for testing
RUN npm install

# Copy the test files into the container
COPY ./tests /app
#RUN chmod -R 777 /app/testimages/1kb.png

# Set the default command to run the tests
CMD ["npm", "test"]
