name: backed-build-production

on:
  pull_request:
    branches: ["main"]
    types : [opened, synchronize]
  push:
    branches: ["feature/ci-cd"]
    paths:
      - 'backend/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd backend
    - run: npm ci
    - run: npm test --if-present
